import type { Metadata } from "next";
import {
  Lora,
  Montserrat_Alternates,
  EB_Garamond,
  Oswald,
} from "next/font/google";
import "./globals.scss";

// const LoraFont = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

// const MontserratAlternatesFont = Montserrat_Alternates({
//   variable: "--montserrat-alternates",
//   subsets: ["latin"],
//   weight: ["100", "300", "500", "700"],
// });

const EBGaramondFont = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

const OswaldFont = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${EBGaramondFont.variable} ${OswaldFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
